version: '3.7'

services:
  loki:
    image: grafana/loki:latest
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/loki-config.yaml
    volumes:
      - ./loki-config.yaml:/etc/loki/loki-config.yaml
    environment:
      - LOKI_LOG_LEVEL=info
    networks:
      - logging-net

  promtail:
    image: grafana/promtail:latest
    volumes:
      - ./promtail-config.yaml:/etc/promtail/promtail-config.yaml
      - ./sample-logs:/var/log/  # Mount your log samples here
    command: -config.file=/etc/promtail/promtail-config.yaml
    depends_on:
      - loki
    networks:
      - logging-net

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning  # Datasource and dashboard configs
      - grafana-data:/var/lib/grafana  # Persist Grafana data
    environment:
      - GF_SECURITY_ADMIN_USER=${GF_ADMIN_USER:-admin}  # Configurable via env vars
      - GF_SECURITY_ADMIN_PASSWORD=${GF_ADMIN_PASSWORD:-admin}
      - GF_AUTH_ANONYMOUS_ENABLED=false  # Disable anonymous access
    depends_on:
      - loki
    networks:
      - logging-net
  log-generator:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./sample-logs:/var/log/sample-logs  # Share the same log directory as Promtail
    networks:
      - logging-net

networks:
  logging-net:
    driver: bridge

volumes:
  grafana-data: