auth_enabled: false

common:
  path_prefix: /loki
  storage:
    filesystem:
      chunks_directory: /loki/chunks
      rules_directory: /loki/rules
  replication_factor: 1
  ring:
    kvstore:
      store: inmemory

server:
  http_listen_port: 3100
  grpc_listen_port: 9095

ingester:
  lifecycler:
    ring:
      kvstore:
        store: inmemory
      replication_factor: 1
  chunk_idle_period: 5m       # Reasonable for testing
  max_chunk_age: 1h          # Reasonable for testing
  chunk_target_size: 1048576 # 1MB, good default

schema_config:
  configs:
    - from: 2025-04-01       # Adjusted to cover your log dates
      store: tsdb            # Switch to TSDB for better performance
      object_store: filesystem
      schema: v13            # Latest schema version
      index:
        prefix: index_
        period: 24h

storage_config:
  tsdb_shipper:              # Replace boltdb-shipper with TSDB
    active_index_directory: /loki/index
    cache_location: /loki/tsdb-cache
  filesystem:
    directory: /loki/chunks

limits_config:
  allow_structured_metadata: true  # Enable for richer metadata
  reject_old_samples: true
  reject_old_samples_max_age: 168h # 7 days, fine for testing
  max_query_length: 720h           # Allow querying up to 30 days

table_manager:
  retention_deletes_enabled: true  # Enable retention
  retention_period: 168h           # Retain logs for 7 days