server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: sample-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: sample-logs
          __path__: /var/log/app.log  
    pipeline_stages:
      - json:
          expressions:
            observed_timestamp_rfc3339: observed_timestamp_rfc3339
            instrumentation_scope: instrumentation_scope
            severity_text: severity_text
            body: body
            resource: resource
            host_name: host_name
            severity_number: severity_number
            span_id: span_id
            trace_id: trace_id
      - labels:
          observed_timestamp_rfc3339:
          severity_text:
          instrumentation_scope:
          resource:
          detected_level:
          filename:
          host_name:
          service_name:
          severity_number:
          span_id:
          trace_id:
      - output:
          source: body  # Use 'body' as the main log line
